# Configurações do Projeto
project:
  name: "top_one_model"
  version: "1.0.0"
  description: "Sistema de Modelagem de Risco de Crédito com Dados Regionais"

# Configurações de Dados
data:
  internal_dataset: "data/internal_data/dataset_interno_top_one.xlsx"
  external_data_dir: "data/external"
  processed_data_dir: "data/processed"
  
# Configurações de Web Scraping
scraping:
  frequency_days: 45
  combustiveis:
    frequency_days: 7
    sources:
      - "anp.gov.br"
      - "precodoscombustiveis.com.br"
  utilities:
    frequency_days: 30
    sources:
      - "aneel.gov.br"
      - "snis.gov.br"
  
# Configurações de Modelagem
modeling:
  risk_spectrum:
    regions:
      - name: "Adimplente Pontual"
        score_range: [0.0, 0.2]
      - name: "Adimplente Lucrativo" 
        score_range: [0.2, 0.4]
      - name: "Risco de Abandono Precoce"
        score_range: [0.4, 0.6]
      - name: "Inadimplente Parcial"
        score_range: [0.6, 0.8]
      - name: "Inadimplente Total"
        score_range: [0.8, 1.0]
  
  retrain_frequency_days: 45
  validation_window_months: 18
  
# Configurações de Monitoramento
monitoring:
  drift_threshold: 0.15
  performance_window_days: 30
  alert_thresholds:
    auc_min: 0.75
    precision_min: 0.70
    recall_min: 0.65
